### ISSUE TITLE
Update imgui

### ISSUE THREAD

**Issue by codecat** [pthom/hello_imgui#11]
Hey there, was hoping to get an imgui update in hello_imgui to fix an issue I was having: https://github.com/ocornut/imgui/issues/3982

I'm not sure how often imgui generally gets updated for hello_imgui, so figured I'd just ask. Thanks! :smiling_face_with_three_hearts:

**Comment by pthom** [comment]
Hello, the imgui submodule is a direct checkout of imgui's docking branch; so that updating is generally a simple update of the submodule. I did it right now ;-) (see https://github.com/pthom/hello_imgui/commit/36237f7a9dc64b5dc0c14f3435d91707340dd14c)

> I'm not sure how often imgui generally gets updated

Hum, when I think of it; i.e once every 2 or 3 months ;-)
But you can also propose PRs, the CI should catch compilation errors.

**Comment by codecat** [comment]
Good to know! Thanks for the quick update! :D
