### ISSUE TITLE
CMake option to disable auto updating

### ISSUE THREAD

**Issue by ariddl** [pthom/hello_imgui#123]
Hello,

Like the library however every time I run cmake my application breaks from a new update to hello_imgui.  Like now my app crashes at startup due to not finding some font. It's really frustrating, and it also takes forever. I just wanted to stay on the version I started with.

Please can you add an easy way to disable auto updates. Thank you.

**Comment by pthom** [comment]
Hello,

In most cases it should not auto-update. What you describe is strange. 
In order to understand your issue more details about how you build your application are needed. Namely I would need to know how did you get HelloImGui: is it via a submodule or (in which case you are responsible for updating it) via [hello_imgui_template](https://github.com/pthom/hello_imgui_template/tree/main), via vcpkg ?

If you are using hello_imgui_template, there might be a reason: look at the [CMakeLists](https://github.com/pthom/hello_imgui_template/blob/main/CMakeLists.txt):
See this extract:
```cmake
# 2/  Option 2: simply fetch hello_imgui during the build
if (NOT TARGET hello_imgui)
    message(STATUS "Fetching hello_imgui")
    include(FetchContent)
    FetchContent_Declare(hello_imgui GIT_REPOSITORY https://github.com/pthom/hello_imgui.git GIT_TAG master)
    FetchContent_MakeAvailable(hello_imgui)
endif()
```

You may want to replace `GIT_TAG master` by a sha1 reference to a particular commit or to a release tag.

**Comment by pthom** [comment]
Please keep me updated. Did this solve your issue?

**Comment by pthom** [comment]
Closing, for lack of answer
