### ISSUE TITLE
Docking Demo Keyboard Input Problems

### ISSUE THREAD

**Issue by frink** [pthom/hello_imgui#4]
On Chrome it seams that the Classic and Docking Demos differ in their keyboard input...

Things that work in the Classic Demo and Not in Docking Demo:

- ioConfigFlags: NavEnabledKeyboard
- Backspace / Back Delete
- Ctrl+A / Select All
- Ctrl+X / Cut
- Ctrl+V / Paste
- Ctrl-C / Copy

Since both are built from the same docking branch I'm confused as to why one would work and the other not...

Thought it was worth a report.

To duplicate go to the Dear Imgui Demo > Configuration and enable ioConfigFlags: NavEnableKeyboard and press down / up / space. After turning this off you can go to Dear Imgui Demo > Widgets > Basic. Type "asdf, Ctrl+A, Ctrl+X, Ctrl+VV, Backspace, Ctrl+C, Ctrl+VV...

This all works fine on the Classic demo but not on the Docking demo... Weird!

**Comment by pthom** [comment]
Nice catch 👍 

This is solved by this [commit](https://github.com/pthom/hello_imgui/commit/6f78ede86e69578abd63cfdaaf09015a6d6edee9) : it was mainly an issue because this demo show how to handle keyboard events via SDL, and you need to return true in the SDL handler in order for them to be further processed.
