### ISSUE TITLE
text blurry when connected to a non-retina external monitor 

### ISSUE THREAD

**Issue by wkjarosz** [pthom/hello_imgui#98]
On macOS with a MacBook Pro, I just noticed the following behavior:

launch a hello imgui app on:
1. macbook with no external monitor connected: HighDPI resolution is detected properly and fonts are crisp
2. macbook with external monitor connected and set to a retina resolution: HighDPI resolution is detected properly and fonts are crisp
3. macbook with external monitor connected and set to a non-retina resolution: HighDPI resolution is seemingly not detected properly and fonts are blurry when moving the window from the non-retina monitor to the main retina display.

I have confirmed this behavior in my own apps, and also the fontawesome example in hello imgui.

Is there a way to handle case 3 above properly?

**Comment by pthom** [comment]
You are experiencing a known quirk with ImGui: see this extract from the [ImGui FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application):

> The reason DPI is not auto-magically solved in stock examples is that we don't yet have a satisfying solution for the "multi-dpi" problem (using the docking branch: when multiple viewport windows are over multiple monitors using different DPI scales). The current way to handle this on the application side is:
> Create and maintain one font atlas per active DPI scale (e.g. by iterating platform_io.Monitors[] before NewFrame()).
    Hook platform_io.OnChangedViewport() to detect when a Begin() call makes a Dear ImGui window change monitor (and therefore DPI).
    In the hook: swap atlas, swap style with correctly sized one, and remap the current font from one atlas to the other (you may need to maintain a remapping table of your fonts at varying DPI scales).


HelloImGui [tries hard to add many additional steps to handle DPI correctly on different platforms](https://pthom.github.io/hello_imgui/book/doc_params.html#dpi-aware-params).
 However, this is a very difficult a time consuming task, since [different platforms, or different app settings handle DPI differently](https://pthom.github.io/hello_imgui/book/doc_api.html#details-on-dpi-handling-on-different-os).

Moving a window between monitors having different DPIs is not handled at the moment, since this would require 1/ changing the font atlas whenever the windows switches to a different monitor, and 2/ adapt the window size to account for the DPI change (on windows).

However, under macOS we might be lucky, since the window physical size (in millimeter) will likely not change when moving from one Retina screen to a non retina screen.

Last week, I was confronted to [this issue](https://github.com/pthom/imgui_bundle/issues/180), which lead me to introduce some settings: 

See [dpi_aware.h](https://pthom.github.io/hello_imgui/book/doc_params.html#dpi-aware-params)

If you create a `hello_imgui.ini` file where you place

```
[DpiAwareParams]
dpiWindowSizeFactor=1
fontRenderingScale=0.5
```

(or if you set those values inside `runnerParams.dpiAwareParams`), you will disconnect HelloImGui automatic DPI detection.

In this case, fonts will be loaded at twice the size and scaled by 0.5 upon rendering, which will likely improve the situation. The fonts will use more texture memory (but it will be the same as when running directly on the retina screen, since in that case HelloImGui will apply `fontRenderingScale=0.5` automatically).

Please keep me informed of the result

**Comment by pthom** [comment]
Thanks,
I took a few minutes to build at  imgui branch of your hdrview project, it looks extremely nice!

**Comment by wkjarosz** [comment]
Thanks!
